### ISSUE TITLE
iOS模拟器上lua报错

### ISSUE THREAD

**Issue by sishui** [rainfiel/ejoy2dx#7]
screenScale: 2.000000
bounds: x:0.000000 y:0.000000 w:320.000000 h:568.000000
...-9220-71F85EC260BB/example.app/script/battle/collide.lua:122: attempt to index a nil value (field '?')
stack traceback:
    ...-9220-71F85EC260BB/example.app/script/battle/collide.lua:122: in function 'battle.collide.get_collide_data'
    ...7A-9220-71F85EC260BB/example.app/script/battle/level.lua:81: in method 'init'
    ...7A-9220-71F85EC260BB/example.app/script/battle/level.lua:130: in function 'battle.level.new'
    ...-D4E3-497A-9220-71F85EC260BB/example.app/script/main.lua:19: in local 'f'
    [string "local path, lua_root, lua_main, startup = ......"]:12: in main chunk

**Comment by rainfiel** [comment]
谢谢提醒，之前ignore掉了工具生成的碰撞数据文件，已经修正：https://github.com/rainfiel/ejoy2dx/commit/21d401dbd1b7fb71caa7a63c741ca093e1ccb3ec
