### ISSUE TITLE
Too few arguments to function call, expected 4, have 3

### ISSUE THREAD

**Issue by sishui** [rainfiel/ejoy2dx#9]
生成的工程 以及自带的例子中
ViewController.m 调用 ejoy2d_fw_touch 的参数个数不对，编译通不过

**Comment by rainfiel** [comment]
https://github.com/rainfiel/ejoy2dx/commit/58758fb23b61fdc73155a4e26fe4dcbb5812f4e3  修正了，支持multi touch，默认传touchid为0

**Comment by sishui** [comment]
测试OK
